batch_size: 32
epochs: 10
lr: 1e-3
clip_grad: 0.0
momentum: 0.9
weight_decay: 5e-4
optimizer: "sgd"
amsgrad: False
scheduler: "cosine"
t_max: float("inf")
step_size: 5
milestones:
  - 7
gamma: 0.1
warmup_epochs: 0
evaluate_every: 1
forgetting_epochs: 7
use_train_aug: False
ssd_dampening_constant: 0.1
ssd_selection_weighting: 0.1

dro_lr: 1